### ISSUE TITLE
BarChartView gets squeezed when device rotated!

### ISSUE THREAD

**Issue by sjd753** [diogobernardino/WilliamChart#147] opened 2016-08-18 14:35 UTC
On rotation of device BarChartView gets either stretched (landscape) or squeezed (portrait). Using in fragment inside CardView and fragment being used in ViewPager.

**Comment by diogobernardino** [comment] 2016-08-31 14:33
I couldn't reproduce it. Do you still have the problem?

**Comment by sjd753** [comment] 2016-09-01 15:57
Yes! Use BarChartView in the fragment and use FragmentPagerAdapter for a viewPager.

**Comment by diogobernardino** [comment] 2016-09-10 15:15
Can you provide a layout?

**Comment by diogobernardino** [comment] 2016-10-08 20:41
As I cannot observe the same in any of my attempts to reproduce the problem, if there's no feedback from your side during the following week I will consider it a problem in your own layout and close the issue.

**Closed** 2016-12-12 18:55 UTC
Labels: bug, on hold
