### ISSUE TITLE
LineChart example give error warning

### ISSUE THREAD

**Issue by radeshf** [diogobernardino/williamchart#282] opened 2020-10-19 09:27 UTC
i use example code to create line bar but give this error warning

`lineChart.gradientFillColors =
            intArrayOf(
                Color.parseColor("#81FFFFFF"),
                Color.TRANSPARENT
            )`

error warning
  

>  Size must be at least 2 and at most 2

it's work fine but give this error warning 
Android studio 4.0.1
library version 3.7.2
compileSdkVersion 30
buildToolsVersion 29.0.3

**Comment by diogobernardino** [comment] 2020-11-07 18:13
Duplicate of #281 .

**Closed by diogobernardino** 2020-11-07 18:13 UTC
