### ISSUE TITLE
bitmap size exceeds 32 bits

### ISSUE THREAD

**Issue by Akariuz** [diogobernardino/WilliamChart#123] opened 2016-04-19 18:26 UTC
Hi, first thank you for your library.

i have a tested on diferent devices and all work well, but in a phone i get **bitmap size exceeds 32 bits** i dont know why is this, its call M4 and has android 5.1 is new and i have tested in older and with less resurces phones and it work great. i dont know what to do i even add the android:largeHeap="true" in the manifest and still dosent work in that phone.

`FATAL EXCEPTION: main
                                                                     Process: com.unia.uniafernanda, PID: 3019
                                                                     java.lang.IllegalArgumentException: bitmap size exceeds 32 bits
                                                                         at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:772)
                                                                         at android.view.View.buildDrawingCacheImpl(View.java:14631)
                                                                         at android.view.View.buildDrawingCache(View.java:14563)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14358)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14376)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at android.view.View.draw(View.java:15507)
                                                                         at android.widget.FrameLayout.draw(FrameLayout.java:658)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14384)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14376)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14376)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at android.view.View.draw(View.java:15507)
                                                                         at android.widget.FrameLayout.draw(FrameLayout.java:658)
                                                                         at android.widget.ScrollView.draw(ScrollView.java:1715)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14384)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14376)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14376)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14376)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14376)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.View.draw(View.java:15204)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
                                                                         at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2787)
                                                                         at android.view.View.draw(View.java:15507)
                                                                         at android.widget.FrameLayout.draw(FrameLayout.java:658)
                                                                         at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2766)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:14384)
                                                                         at android.view.View.getDisplayList(View.java:14413)
                                                                         at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:279)
                                                                        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:285`

**Comment by diogobernardino** [comment] 2016-04-20 07:28
The limitation seem to come from android.graphics.Bitmap not from WilliamChart, I'm afraid I won't be able to help you.

**Comment by liganisme** [comment] 2016-06-15 03:14
same problem，how to resolve？

**Comment by diogobernardino** [comment] 2016-06-15 08:15
Even finding it strange, it's maybe worth to check if there's any place in the code that can produce it. I will do so once I have some time.
In any case, as I don't know the issue, I cannot tell you how to solve it. It might be useful if you could place here your chart customization and in which phones does it seem to break.

**Comment by diogobernardino** [comment] 2016-10-08 20:13
Still couldn't find evidences that the problem is being triggered by the way ```Toolip``` is implemented or managed by ```ChartView```, as I don't actually handle the images inside the layouts which are set to the ```Tooltip```, I simply inflate the layout and add it to the view. For the time being there's nothing I can do on this. Maybe if someone shares something more I will be able to look into it again, otherwise I will be closing the issue during the following weeks.

**Closed** 2016-12-12 18:56 UTC
Labels: on hold
